# Generated by Django 6.0 on 2025-12-30 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('composer', models.CharField(max_length=256)),
                ('arranged_by', models.CharField(max_length=256)),
                ('part_of_mass', models.CharField(choices=[('entrance', 'Entrance Procession'), ('penitential', 'Penitential Act'), ('gloria', 'Gloria'), ('collect', 'Collect'), ('first_reading', 'First Reading'), ('responsorial', 'Responsorial Psalm'), ('second_reading', 'Second Reading'), ('gospel', 'Gospel Reading'), ('homily', 'Homily'), ('creed', 'Creed'), ('prayers', 'Prayer of the Faithful'), ('offertory', 'Presentation of Gifts'), ('eucharistic_prayer', 'Eucharistic Prayer'), ('our_father', "Lord's Prayer"), ('sign_of_peace', 'Sign of Peace'), ('communion', 'Communion'), ('prayer_after', 'Prayer after Communion'), ('blessing', 'Blessing'), ('dismissal', 'Dismissal')])),
                ('season', models.CharField(choices=[('lent', 'Lent'), ('easter', 'Easter'), ('christmas', 'Christmas'), ('advent', 'Advent'), ('ordinary', 'Ordinary Time')], default='pending_approval')),
                ('mtn', models.BooleanField(default=False)),
                ('mtn_number', models.CharField(max_length=256)),
                ('youtube_link', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('published', 'Published')])),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_sheet', models.FileField(upload_to='music_sheets/')),
                ('ms_version', models.CharField(max_length=256)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucath_songs.song')),
            ],
        ),
        migrations.CreateModel(
            name='Mp3File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp3_file', models.FileField(upload_to='music_sheets/')),
                ('mp3_version', models.CharField(max_length=256)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucath_songs.song')),
            ],
        ),
        migrations.CreateModel(
            name='MidiFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midi_file', models.FileField(upload_to='midi_files/')),
                ('midi_version', models.CharField(max_length=256)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucath_songs.song')),
            ],
        ),
    ]
