# Generated by Django 6.0 on 2026-01-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucath_songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='mtn',
            new_name='mto',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='mtn_number',
            new_name='mto_number',
        ),
        migrations.AlterField(
            model_name='mp3file',
            name='mp3_file',
            field=models.FileField(upload_to='mp3_files/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='part_of_mass',
            field=models.CharField(choices=[('entrance', 'Entrance Procession'), ('penitential', 'Penitential Act / Kyrie'), ('gloria', 'Gloria'), ('collect', 'Collect'), ('responsorial', 'Responsorial Psalm'), ('meditation', 'Meditation'), ('gospel', 'Gospel Acclamation'), ('creed', 'Creed'), ('prayers', 'Prayers of the Faithful'), ('offertory', 'Offertory'), ('our_father', "Lord's Prayer"), ('sign_of_peace', 'Sign of Peace'), ('communion', 'Eucharist'), ('blessing', 'Blessing'), ('dismissal', 'Dismissal / Recession'), ('others', 'Others')]),
        ),
    ]
