# Generated by Django 6.0 on 2026-01-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucath_songs', '0002_rename_mtn_song_mto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='season',
            field=models.CharField(choices=[('lent', 'Lent'), ('easter', 'Easter'), ('christmas', 'Christmas'), ('advent', 'Advent'), ('ordinary', 'Ordinary Time')], default='ordinary'),
        ),
        migrations.AlterField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('published', 'Published')], default='pending_approval'),
        ),
    ]
