# Generated by Django 6.0 on 2026-01-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucath_songs', '0003_alter_song_season_alter_song_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicsheet',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='music_thumbnails/'),
        ),
    ]
