# Generated by Django 6.0 on 2026-01-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucath_songs', '0004_musicsheet_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midifile',
            name='midi_version',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mp3file',
            name='mp3_version',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='musicsheet',
            name='ms_version',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
