# Generated by Django 6.0 on 2026-01-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucath_songs', '0005_alter_midifile_midi_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midifile',
            name='midi_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='season',
            field=models.CharField(choices=[('lent', 'Lent'), ('easter', 'Easter'), ('christmas', 'Christmas'), ('advent', 'Advent'), ('passion', 'Passion For Christ'), ('ordinary', 'Ordinary Time')], default='ordinary'),
        ),
    ]
