# Generated by Django 6.0 on 2026-02-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucath_songs', '0006_midifile_midi_link_alter_song_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicsheet',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='part_of_mass',
            field=models.CharField(choices=[('entrance', 'Entrance Procession'), ('penitential', 'Penitential Act / Kyrie'), ('gloria', 'Gloria'), ('collect', 'Collect'), ('responsorial', 'Responsorial Psalm'), ('meditation', 'Meditation'), ('gospel', 'Gospel Acclamation'), ('creed', 'Creed'), ('prayers', 'Prayers of the Faithful'), ('offertory', 'Offertory'), ('our_father', "Lord's Prayer"), ('sign_of_peace', 'Sign of Peace'), ('communion', 'Eucharist'), ('blessing', 'Blessing'), ('dismissal', 'Dismissal / Recession'), ('baptism', 'Baptism'), ('others', 'Others')]),
        ),
    ]
