# Generated by Django 6.0 on 2026-02-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucath_songs', '0007_musicsheet_slug_alter_song_part_of_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='archive_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
