# Generated by Django 6.0 on 2026-02-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucath_songs', '0008_song_archive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
