# Generated by Django 6.0 on 2026-02-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucath_songs', '0009_alter_song_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mto_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
